# Direct + btw MCP Session Configuration
# Auto-generated by direct::init_project()

# Load required packages silently
suppressPackageStartupMessages({
  library(direct)
  library(btw)
  library(mcptools)
})

# Register this RStudio session with the MCP server
# This allows Claude Desktop to interact with this session
btw::btw_mcp_session()

# Welcome message
cat('\n✅ Direct + btw session registered\n')
cat('📁 Workspace:', getwd(), '\n')
cat('🎬 Direct tools: Active execution with security\n')
cat('📊 btw tools: Passive observation and documentation\n\n')
