# Direct MCP Server Configuration
# Auto-generated by direct::init_project()

# Load required packages
suppressPackageStartupMessages({
  library(direct)
  library(mcptools)
})

# Start MCP server with direct tools
mcptools::mcp_session()

# Welcome message
cat('\n✅ Direct MCP server started\n')
cat('📁 Workspace:', getwd(), '\n')
cat('🛡️  Security features active\n\n')
