# ============================================================================
# Setup Functions for Direct Package
# ============================================================================

#' Initialize Direct in Current Project
#' 
#' Creates a .Rprofile file in the current project directory that loads
#' the direct package and starts the MCP server when the project is opened.
#' 
#' @param force Logical indicating whether to overwrite existing .Rprofile (default: FALSE)
#' @return Invisible NULL
#' @export
#' @examples
#' \dontrun{
#' # Initialize direct in your project
#' init_project()
#' 
#' # Force overwrite existing .Rprofile
#' init_project(force = TRUE)
#' }
init_project <- function(force = FALSE) {
  
  rprofile_path <- file.path(getwd(), ".Rprofile")
  
  # Check if .Rprofile already exists
  if (file.exists(rprofile_path) && !force) {
    message("⚠️  .Rprofile already exists in this project!")
    message("   Use init_project(force = TRUE) to overwrite")
    message("   Current file: ", rprofile_path)
    return(invisible(NULL))
  }
  
  # Get template from inst/templates
  template_path <- system.file("templates", ".Rprofile", package = "direct")
  
  if (!file.exists(template_path)) {
    # Fallback: create template directly
    template_content <- c(
      "# Direct MCP Server Configuration",
      "# Auto-generated by direct::init_project()",
      "",
      "# Load required packages",
      "suppressPackageStartupMessages({",
      "  library(direct)",
      "  library(mcptools)",
      "})",
      "",
      "# Start MCP server with direct tools",
      "mcptools::mcp_session()",
      "",
      "# Welcome message",
      "cat('\\n✅ Direct MCP server started\\n')",
      "cat('📁 Workspace:', getwd(), '\\n')",
      "cat('🛡️  Security features active\\n\\n')"
    )
  } else {
    template_content <- readLines(template_path)
  }
  
  # Write .Rprofile
  writeLines(template_content, rprofile_path)
  
  # Initialize audit configuration
  init_audit_config()
  
  message("✅ Project initialized successfully!")
  message("📁 Created: ", rprofile_path)
  message("📁 Created: .direct/config.yml")
  message("")
  message("Next steps:")
  message("  1. Run show_claude_config() to get Claude Desktop configuration")
  message("  2. Add the configuration to Claude Desktop settings")
  message("  3. Restart RStudio for changes to take effect")
  message("  4. Restart Claude Desktop")
  
  invisible(NULL)
}

#' Show Claude Desktop MCP Configuration
#' 
#' Displays the JSON configuration snippet that needs to be added to
#' Claude Desktop's config file.
#' 
#' @param project_path Optional path to project (default: current directory)
#' @return Invisible character string with JSON configuration
#' @export
#' @examples
#' \dontrun{
#' # Show configuration for current project
#' show_claude_config()
#' 
#' # Show configuration for specific project
#' show_claude_config("/path/to/my/project")
#' }
show_claude_config <- function(project_path = getwd()) {
  
  project_path <- normalizePath(project_path, mustWork = FALSE)
  
  # Create JSON configuration
  # Use Rscript and the new start_mcp_server() function
  config <- '{
  "mcpServers": {
    "r-direct": {
      "command": "Rscript",
      "args": [
        "-e",
        "direct::start_mcp_server()"
      ]
    }
  }
}'
  
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  message("📋 CLAUDE DESKTOP CONFIGURATION")
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  message("")
  message("1. Open Claude Desktop configuration:")
  message("   - macOS: ~/Library/Application Support/Claude/claude_desktop_config.json")
  message("   - Windows: %APPDATA%\\Claude\\claude_desktop_config.json")
  message("   - Linux: ~/.config/Claude/claude_desktop_config.json")
  message("")
  message("2. Add or merge this configuration:")
  message("")
  cat(config)
  message("")
  message("")
  message("3. Save the file and restart Claude Desktop")
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  
  invisible(config)
}

#' Check Direct Setup
#' 
#' Verifies that direct and required packages are properly installed and
#' the MCP server is configured correctly.
#' 
#' @return Invisible list with check results
#' @export
#' @examples
#' \dontrun{
#' # Check if everything is set up correctly
#' check_setup()
#' }
check_setup <- function() {
  
  results <- list(
    direct_installed = FALSE,
    mcptools_installed = FALSE,
    ellmer_installed = FALSE,
    rprofile_exists = FALSE,
    rstudio_available = FALSE
  )
  
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  message("🔍 CHECKING DIRECT SETUP")
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  message("")
  
  # Check direct
  if (requireNamespace("direct", quietly = TRUE)) {
    results$direct_installed <- TRUE
    message("✅ direct package installed")
  } else {
    message("❌ direct package NOT installed")
  }
  
  # Check mcptools
  if (requireNamespace("mcptools", quietly = TRUE)) {
    results$mcptools_installed <- TRUE
    message("✅ mcptools package installed")
  } else {
    message("❌ mcptools package NOT installed")
    message("   Install with: install.packages('mcptools')")
  }
  
  # Check ellmer
  if (requireNamespace("ellmer", quietly = TRUE)) {
    results$ellmer_installed <- TRUE
    message("✅ ellmer package installed")
  } else {
    message("❌ ellmer package NOT installed")
    message("   Install with: install.packages('ellmer')")
  }
  
  # Check .Rprofile
  rprofile_path <- file.path(getwd(), ".Rprofile")
  if (file.exists(rprofile_path)) {
    results$rprofile_exists <- TRUE
    message("✅ .Rprofile exists in project")
  } else {
    message("⚠️  .Rprofile NOT found in project")
    message("   Run: init_project()")
  }
  
  # Check RStudio
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    results$rstudio_available <- TRUE
    message("✅ RStudio available")
  } else {
    message("⚠️  RStudio not available (some features require RStudio)")
  }
  
  message("")
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  
  all_ok <- all(unlist(results[c("direct_installed", "mcptools_installed", "ellmer_installed")]))
  
  if (all_ok) {
    message("✅ Setup looks good!")
  } else {
    message("⚠️  Some issues found - see above for details")
  }
  
  message("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  
  invisible(results)
}
